version: '3.8'
services:
  kibana:
    build: .
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elastic
    ports:
      - "5601:5601"
  elasticsearch:
    build: "robertrm/docker-elasticsearch-arm64:7.10.1"
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elastic
    ports:
      - "9200:9200"
    volumes:
      - data01:/usr/share/elasticsearch/data
volumes:
  data01:
networks:
  elastic:
    driver: overlay
